### ISSUE TITLE
Test API calls on Postman

### ISSUE THREAD

**Issue by pranavjanjam** [os-ucsd/leetles#10]
# Subtasks
- [x] Set up Postman
- [ ] Create GCal account
- [ ] Test API calls
