### ISSUE TITLE
Make Google Calendar API key and OAuth ID secret

### ISSUE THREAD

**Issue by phedayat** [os-ucsd/leetles#13]
# Subtasks
- [ ] Get files representing the key and ID
- [ ] Connect them to apiConnect.js (or whatever works)
- [ ] Add any key/ID-related files to .gitignore

# Acceptance Criteria
If the GCal API quickstart still runs properly when using the "secret" key and ID.

## Branch
`js-backend`
